# Generated by Django 4.2.7 on 2024-01-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(default='', upload_to='main_app/static/uploads_resumes/'),
        ),
    ]
